trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
variables:
  dockerRegistryServiceConnection: '<SERVICE_CONNECTION_NAME>'
  imageRepository: '<ACR_REPOSITORY>'
  containerRegistry: '<ACR_LOGIN_SERVER>'
  dockerfilePath: '**/Dockerfile'
steps:
# - script: |
#     echo Add other tasks to build, test, and deploy the project.
#     docker login <acr-name>.azurecr.io -u <acr-username> -p <acr_password>
#   displayName: 'Login to acr'
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'build'
    Dockerfile: '$(dockerfilePath)'
    arguments: |
      --build-arg DB_NAME=$(DB_NAME)
      --build-arg DB_HOST=$(DB_HOST)
      --build-arg DB_PASS=$(DB_PASS)
      --build-arg DB_PORT=$(DB_PORT)
      --build-arg DB_SCHEMA=$(DB_SCHEMA)
      --build-arg DB_TYPE=$(DB_TYPE)
      --build-arg DB_USER=$(DB_USER)
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'push'
    tags: $(Build.BuildId)
