test_project:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev
